DEFAULT_INVENTORY = [
    {"name": "サラダ油（8個入り）", "ideal": 8},
    {"name": "出汁セット", "ideal": 3},
    {"name": "タコ（1袋）", "ideal": 2},
    {"name": "そーす", "ideal": 0},
    {"name": "まよ", "ideal": 0},
    {"name": "天かす", "ideal": 0},
    {"name": "ガスボンベ（◯本）", "ideal": 0},
    {"name": "かつお", "ideal": 0},
    {"name": "ふくろ", "ideal": 0},
    {"name": "粉", "ideal": 0},
    {"name": "はし", "ideal": 0},
    {"name": "タコせん", "ideal": 0},
    {"name": "油", "ideal": 0},
    {"name": "しょうゆ", "ideal": 0},
    {"name": "青のり", "ideal": 0},
    {"name": "卵", "ideal": 0},
    {"name": "長いも", "ideal": 0},
    {"name": "たこ", "ideal": 0},
    {"name": "白だし", "ideal": 0},
    {"name": "紅生姜", "ideal": 0},
    {"name": "出汁液", "ideal": 0},
]
